[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "valkey-migrate"
dynamic = ["version"]
description = "Tools and instructions to migrate between Redis-compatible databases (e.g., Redis/Dragonfly to Valkey)"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["click==8.4.1", "valkey==6.1.1"]

[project.scripts]
vk_migrate = "src.cli:cli"

[tool.uv]
package = true
